# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-13 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20161113_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='file_apk',
            field=models.FileField(null=True, upload_to='projects/apks/'),
        ),
        migrations.AddField(
            model_name='project',
            name='url_appstore',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='url_playstore',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='url_website',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='url_winstore',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.FileField(null=True, upload_to='projects/'),
        ),
    ]
